services:
    # Définition des paramètres par défaut pour tous les services
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Charge automatiquement toutes les classes dans le dossier src/ (sauf celles exclues)
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # Ici, on ajoute explicitement notre subscriber (si nécessaire)
    App\EventSubscriber\CalendarSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }
