# config/services.yaml
parameters:
    avatars_directory: '%kernel.project_dir%/public/uploads/avatars'
    materiels_directory: '%kernel.project_dir%/public/images/materiel'
    # --- AJOUT DU NOUVEAU PARAMÈTRE POUR LES IMAGES DE LA GALERIE ---
    gallery_images_directory: '%kernel.project_dir%/public/images/gallery' # Dossier pour les images de la galerie

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        # public: false # Laissé pour cohérence, mais souvent le défaut

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            # Correction de l'exclusion multiple, une seule suffit pour le chemin
            - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # Configuration pour CalendarSubscriber (inchangée)
    App\EventSubscriber\CalendarSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    # Configuration pour MaterielController (inchangée)
    App\Controller\MaterielController:
        bind:
            $materielsDirectory: '%materiels_directory%'

    # Configuration pour GoogleCalendarService (inchangée)
    App\Service\GoogleCalendarService:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $logger: '@?logger'

    # --- AJOUT DE LA CONFIGURATION POUR AdminGalleryController ---
    App\Controller\AdminGalleryController:
        arguments: # Utiliser arguments car on l'injecte dans le constructeur
            $galleryImagesDirectory: '%gallery_images_directory%'